{
  imports = [
    ./discord.nix
    ./organicmaps.nix
    ./git.nix
    ./firefox.nix
    ./bash.nix
    ./thunderbird.nix
    ./kodi.nix
    ./temurin.nix
    ./prism-launcher.nix
    ./pass.nix
    ./kitty.nix
    ./gh.nix
    ./tor-browser.nix
    ./qbittorrent.nix
    ./gimp.nix
    ./tuxguitar.nix
    ./mpv.nix
    ./yt-dlp.nix
    ./rssguard.nix
    ./agenix.nix
    ./openmw.nix
    ./zoom.nix
    ./libreoffice.nix
    ./zathura.nix
    ./calibre.nix
    ./rnote.nix
    ./flameshot.nix
  ];
}
